package com.dreamwalker.knu2018.dteacher.Const

/**
 * Created by KNU2017 on 2018-02-01.
 */

object IntentConst {

    val SIGNUP_EXTRA_DATA_0 = "SIGNUP_EXTRA_DATA_0"
    val SIGNUP_EXTRA_DATA_1 = "SIGNUP_EXTRA_DATA_1"
    val SIGNUP_EXTRA_DATA_2 = "SIGNUP_EXTRA_DATA_2"
    val SIGNUP_EXTRA_DATA_3 = "SIGNUP_EXTRA_DATA_3"
    val SIGNUP_EXTRA_DATA_4 = "SIGNUP_EXTRA_DATA_4"
    val SIGNUP_EXTRA_DATA_5 = "SIGNUP_EXTRA_DATA_5"
    val SIGNUP_EXTRA_DATA_6 = "SIGNUP_EXTRA_DATA_6"
    val SIGNUP_REGISTER_TYPE = "SIGNUP_REGISTER_TYPE"

    val DIARY_PAGE_FRAGMENT_NUM = "DIARY_PAGE_FRAGMENT_NUM"

    val WRITE_DRUG_TYPE = "WRITE_DRUG_TYPE"
    val WEB_URL = "WEB_URL"

}
